version: '3.8'
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # Prevents host's node_modules from overriding container's
    environment:
      NODE_ENV: development # Or production, depending on your needs